# Generated by Django 2.0 on 2019-10-18 15:57

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='文章', verbose_name='文章')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='发布时间', verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '公司简介',
                'verbose_name_plural': '公司简介',
                'db_table': 'tb_company',
                'ordering': ['id', '-created_time'],
            },
        ),
        migrations.CreateModel(
            name='AboutType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_type', models.CharField(help_text='关于我们', max_length=20, verbose_name='关于我们')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='发布时间', verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '关于我们',
                'verbose_name_plural': '关于我们',
                'db_table': 'tb_about',
                'ordering': ['id', '-created_time'],
            },
        ),
        migrations.AddField(
            model_name='about',
            name='about_type',
            field=models.ForeignKey(help_text='关于我们', on_delete=django.db.models.deletion.DO_NOTHING, to='about.AboutType', verbose_name='关于我们'),
        ),
    ]
