# Generated by Django 2.0 on 2019-10-16 14:35

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='招聘岗位', max_length=20, verbose_name='招聘岗位')),
                ('author', models.CharField(help_text='发布人', max_length=20, verbose_name='发布人')),
                ('salary', models.CharField(help_text='薪资待遇', max_length=20, verbose_name='薪资待遇')),
                ('responsibilities', ckeditor_uploader.fields.RichTextUploadingField(help_text='岗位要求', verbose_name='岗位要求')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='岗位职责', verbose_name='岗位职责')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='发布时间', verbose_name='发布时间')),
                ('img_url', models.ImageField(blank=True, default='', upload_to='recruit')),
            ],
            options={
                'verbose_name': '招聘中心',
                'verbose_name_plural': '招聘中心',
                'db_table': 'tb_recruit',
                'ordering': ['id', '-created_time'],
            },
        ),
    ]
