# Generated by Django 2.0 on 2019-10-19 10:30

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Golds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='新闻标题', max_length=50, verbose_name='新闻标题')),
                ('author', models.CharField(help_text='新闻来源', max_length=20, verbose_name='新闻来源')),
                ('read_num', models.IntegerField(default=0, help_text='阅读次数', verbose_name='阅读次数')),
                ('text', models.TextField(help_text='文章摘要', max_length=500, verbose_name='文章摘要')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='文章', verbose_name='文章')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='发布时间', verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '黄金新闻',
                'verbose_name_plural': '黄金新闻',
                'db_table': 'tb_gold',
                'ordering': ['id', '-created_time'],
            },
        ),
        migrations.CreateModel(
            name='GoldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_type', models.CharField(help_text='黄金学堂', max_length=20, verbose_name='黄金学堂')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='发布时间', verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '黄金学堂',
                'verbose_name_plural': '黄金学堂',
                'db_table': 'tb_gold_type',
                'ordering': ['id', '-created_time'],
            },
        ),
        migrations.AddField(
            model_name='golds',
            name='gold_type',
            field=models.ForeignKey(help_text='黄金学堂', on_delete=django.db.models.deletion.DO_NOTHING, to='golds.GoldType', verbose_name='黄金学堂'),
        ),
    ]
