# Generated by Django 2.0 on 2019-10-17 16:02

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=50, verbose_name='标题')),
                ('author', models.CharField(help_text='发布人', max_length=50, verbose_name='发布人')),
                ('read_num', models.IntegerField(default=0, help_text='阅读次数', verbose_name='阅读次数')),
                ('text', models.TextField(default='', help_text='文章摘要', max_length=300, verbose_name='文章摘要')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='文章', verbose_name='文章')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='发布时间', verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '规则条例',
                'verbose_name_plural': '规则条例',
                'db_table': 'tb_rule',
                'ordering': ['id', '-created_time'],
            },
        ),
        migrations.CreateModel(
            name='RuleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(help_text='制度与规则', max_length=20, verbose_name='制度与规则')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='发布时间', verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '制度与规则',
                'verbose_name_plural': '制度与规则',
                'db_table': 'tb_rule_type',
                'ordering': ['id', '-created_time'],
            },
        ),
        migrations.AddField(
            model_name='rule',
            name='rule_type',
            field=models.ForeignKey(help_text='制度与规则', on_delete=django.db.models.deletion.DO_NOTHING, to='rule.RuleType', verbose_name='制度与规则'),
        ),
    ]
