# Generated by Django 2.0 on 2019-10-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='down_load',
            field=models.FileField(blank=True, default='', max_length=200, upload_to='source', verbose_name='下载路径'),
        ),
    ]
