# Generated by Django 2.0 on 2019-10-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0002_rule_down_load'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='down_load',
        ),
    ]
